type TopScore {
    identifier: String
    fullname: String
    player_identifier: String
    nationality: String
    number: Int
    position: String
    goals: Int
    penalties: Int
    matches: Int
    team: String
    team_identifier: String
}

input LeagueInput {
    league_slug: String
    season_slug: String
}

extend type Query {
    getLeageTopScore(leagueInput: LeagueInput): [TopScore]
}
